[phases.setup]
nixPkgs = ['nodejs_23', 'nodePackages.pnpm']

[phases.install]
cmds = ['pnpm i --frozen-lockfile']

[phases.build]
cmds = ['pnpm exec prisma generate', 'pnpm build']

[start]
cmd = 'pnpm start'
